server:
  port: 8080
  servlet:
    context-path: /
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BlogDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type: trace
        show_sql: true
        generate_statistics: true
        globally_quoted_identifiers: true
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

# 添加Hibernate的详细日志配置
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-prefix: ""
      capital-mode: true
  type-aliases-package: com.example.blogbackend.entity

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 一天 

deepseek:
  api:
    key: sk-9bcae52a34314845a6b5b6fba5be1335
    url: https://api.deepseek.com/v1 